version: "2"

services:
  pocketbase:
    build: .
    container_name: pocketbase
    environment:
      - PB_VERSION="0.21.2"
    ports:
      - "8090:8080"
    volumes:
      - ./pb_data/:/pb/pb_data/
      - ./pb_migrations/:/pb/pb_migrations/
      - ./pb_hooks/:/pb/pb_hooks/
